# Generated by Django 3.2.8 on 2024-02-09 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Координаты',
                'verbose_name_plural': 'Координаты',
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spring', models.CharField(choices=[('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б')], max_length=3, verbose_name='Весна')),
                ('summer', models.CharField(choices=[('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б')], max_length=3, verbose_name='Лето')),
                ('autumn', models.CharField(choices=[('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б')], max_length=3, verbose_name='Осень')),
                ('winter', models.CharField(choices=[('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б')], max_length=3, verbose_name='Зима')),
            ],
            options={
                'verbose_name': 'Уровень сложности',
                'verbose_name_plural': 'Уровни сложности',
            },
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('status', models.CharField(choices=[('NW', 'новый'), ('PN', 'в обработке'), ('AC', 'принят'), ('RJ', 'отклонён')], default='NW', max_length=2, verbose_name='Статус записи')),
                ('beauty_title', models.CharField(max_length=255, verbose_name='Тип объекта')),
                ('title', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('other_titles', models.CharField(max_length=255, verbose_name='Другое название')),
                ('connect', models.CharField(max_length=255, verbose_name='Подключение')),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='new_pereval.coords', verbose_name='Координаты')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_pereval.levels', verbose_name='Уровень сложности')),
            ],
            options={
                'verbose_name': 'Перевал',
                'verbose_name_plural': 'Перевалы',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='Электронная почта')),
                ('fam', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('otc', models.CharField(blank=True, max_length=40, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона с кодом страны')),
            ],
            options={
                'verbose_name': 'Турист',
                'verbose_name_plural': 'Туристы',
            },
        ),
        migrations.CreateModel(
            name='PassImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение')),
                ('pass_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='new_pereval.pass', verbose_name='Перевал')),
            ],
        ),
        migrations.AddField(
            model_name='pass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_pereval.users', verbose_name='Турист'),
        ),
    ]
